// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwheOtB9jZ-3fewrBQwgbqoNyrGUNW1XY',
    appId: '1:355132882847:web:42bb311bb6395812a747aa',
    messagingSenderId: '355132882847',
    projectId: 'grocery-task-jakob',
    authDomain: 'grocery-task-jakob.firebaseapp.com',
    storageBucket: 'grocery-task-jakob.appspot.com',
    measurementId: 'G-HDM83BCGFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeXQrLB06nu4QXkMp01BIxSLtu4MqtzT0',
    appId: '1:355132882847:android:33204532d2e773a4a747aa',
    messagingSenderId: '355132882847',
    projectId: 'grocery-task-jakob',
    storageBucket: 'grocery-task-jakob.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_-wIaSC7gc4a2YCKX3KBLlGDlPV1oPOg',
    appId: '1:355132882847:ios:e76573faefd650c5a747aa',
    messagingSenderId: '355132882847',
    projectId: 'grocery-task-jakob',
    storageBucket: 'grocery-task-jakob.appspot.com',
    iosBundleId: 'com.example.groceryTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_-wIaSC7gc4a2YCKX3KBLlGDlPV1oPOg',
    appId: '1:355132882847:ios:e76573faefd650c5a747aa',
    messagingSenderId: '355132882847',
    projectId: 'grocery-task-jakob',
    storageBucket: 'grocery-task-jakob.appspot.com',
    iosBundleId: 'com.example.groceryTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwheOtB9jZ-3fewrBQwgbqoNyrGUNW1XY',
    appId: '1:355132882847:web:6c1191b6ec66d47fa747aa',
    messagingSenderId: '355132882847',
    projectId: 'grocery-task-jakob',
    authDomain: 'grocery-task-jakob.firebaseapp.com',
    storageBucket: 'grocery-task-jakob.appspot.com',
    measurementId: 'G-1J8ZT4P0P0',
  );
}
